#!/bin/sh
# vim:set ts=2 sw=2 et:

if [ $1 = "post-install" ]; then
  shift
  pkgname="$1"
  installdir="$2"

  if grep "/usr/share/glib-2.0/schemas" $installdir/manifest > /dev/null 2>&1; then
    echo "Compiling GLib schemas..."
    glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null 2>&1
  fi
fi
