#!/bin/sh
# vim:set ts=2 sw=2 et:

if [ $1 = "post-build" ]; then
    shift
    [ -f $2/usr/share/info/dir ] && rm $2/usr/share/info/dir
fi

if [ $1 = "post-install" ]; then
  shift
  pkgname="$1"
  installdir="$2"

  if grep "/usr/share/info" $installdir/manifest > /dev/null 2>&1; then
    echo "Updating infodir..."
    find /usr/share/info -type f | while read -r file; do
      case $file in 
        */dir|*/dir.gz|*/dir.old|*/dir.old.gz|*-[0-9]|*-[0-9].gz|*-[1-9][0-9]|*-[1-9][0-9].gz|*.png)
        continue
        ;;
      *)
        install-info $file /usr/share/info/dir
        ;;
      esac
    done
  fi
fi
